export const minimal = {
  name: 'minimal' as const,
  label: 'Clean & Minimal',
  colors: {
    background: '#FAFAFA',
    surface: '#FFFFFF',
    surfaceSecondary: '#F5F5F5',
    text: '#1A1A1A',
    textSecondary: '#6B7280',
    textTertiary: '#9CA3AF',
    primary: '#2563EB',
    primaryLight: '#DBEAFE',
    accent: '#7C3AED',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    tabBar: '#FFFFFF',
    tabBarBorder: '#E5E7EB',
    tabBarActive: '#2563EB',
    tabBarInactive: '#9CA3AF',
    card: '#FFFFFF',
    shadow: 'rgba(0, 0, 0, 0.05)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 16,
    full: 999,
  },
  typography: {
    heading: { fontSize: 28, fontWeight: '700' as const },
    subheading: { fontSize: 20, fontWeight: '600' as const },
    body: { fontSize: 16, fontWeight: '400' as const },
    caption: { fontSize: 13, fontWeight: '400' as const },
    label: { fontSize: 14, fontWeight: '500' as const },
  },
};
