export const playful = {
  name: 'playful' as const,
  label: 'Colorful & Playful',
  colors: {
    background: '#FFF8F0',
    surface: '#FFFFFF',
    surfaceSecondary: '#FFF1E6',
    text: '#1F1235',
    textSecondary: '#6B5B7B',
    textTertiary: '#A89BB5',
    primary: '#FF6B6B',
    primaryLight: '#FFE0E0',
    accent: '#4ECDC4',
    border: '#F0E6FF',
    borderLight: '#FFF1E6',
    success: '#2ECC71',
    warning: '#FFB347',
    error: '#FF6B6B',
    tabBar: '#FFFFFF',
    tabBarBorder: '#F0E6FF',
    tabBarActive: '#FF6B6B',
    tabBarInactive: '#A89BB5',
    card: '#FFFFFF',
    shadow: 'rgba(255, 107, 107, 0.08)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 10,
    md: 16,
    lg: 24,
    full: 999,
  },
  typography: {
    heading: { fontSize: 28, fontWeight: '700' as const },
    subheading: { fontSize: 20, fontWeight: '600' as const },
    body: { fontSize: 16, fontWeight: '400' as const },
    caption: { fontSize: 13, fontWeight: '400' as const },
    label: { fontSize: 14, fontWeight: '500' as const },
  },
};
